<?php

namespace Cms\Modules\Auth\Tests;

use Cms\Modules\Auth\AuthServiceProvider;
use Cms\Modules\Core\Tests\CoreTestCase;

abstract class AuthTestCase extends CoreTestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function getPackageProviders($app): array
    {
        return [
            AuthServiceProvider::class,
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        // perform environment setup
    }
}
