<?php

namespace Cms\Modules\TodoList\Tests;

use Cms\Modules\TodoList\TodoListServiceProvider;
use Cms\Modules\Core\Tests\CoreTestCase;

abstract class TodoListTestCase extends CoreTestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function getPackageProviders($app): array
    {
        return [
            TodoListServiceProvider::class,
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        // perform environment setup
    }
}

